import requests
from bs4 import BeautifulSoup
import re

players = {
    "Abortion": "https://www.who.int/news-room/fact-sheets/detail/abortion",
    "abuse-of-older-people":"https://www.who.int/news-room/fact-sheets/detail/abuse-of-older-people",
    "Adolescent-and-young-adult-health":"https://www.who.int/news-room/fact-sheets/detail/adolescents-health-risks-and-solutions",
    "Adolescent pregnancy":"https://www.who.int/news-room/fact-sheets/detail/adolescent-pregnancy",
    "Ageing and health":"https://www.who.int/news-room/fact-sheets/detail/ageing-and-health",
    "Alcohol":"https://www.who.int/news-room/fact-sheets/detail/alcohol",
    "Ambient (outdoor) air pollution":"https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health",
    "anaemia":"https://www.who.int/news-room/fact-sheets/detail/anaemia",
    "Animal bites":"https://www.who.int/news-room/fact-sheets/detail/animal-bites",
    "Antimicrobial resistance":"https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance",
    "Anxiety disorders":"https://www.who.int/news-room/fact-sheets/detail/anxiety-disorders",
    "Arsenic":"https://www.who.int/news-room/fact-sheets/detail/arsenic",
    "Asbestos":"https://www.who.int/news-room/fact-sheets/detail/asbestos",
    "assistive-technology":"https://www.who.int/news-room/fact-sheets/detail/assistive-technology",
    "asthma":"https://www.who.int/news-room/fact-sheets/detail/asthma",
    "autism":"https://www.who.int/news-room/fact-sheets/detail/autism-spectrum-disorders",
    "bacterial-vaginosis":"https://www.who.int/news-room/fact-sheets/detail/bacterial-vaginosis",
    "biodiversity":"https://www.who.int/news-room/fact-sheets/detail/biodiversity",
    "bipolar-disorder":"https://www.who.int/news-room/fact-sheets/detail/bipolar-disorder",
    "blindness-and-visual-impairment":"https://www.who.int/news-room/fact-sheets/detail/blindness-and-visual-impairment",
    "blood-safety-and-availability":"https://www.who.int/news-room/fact-sheets/detail/blood-safety-and-availability",
    "botulism":"https://www.who.int/news-room/fact-sheets/detail/botulism",
    "breast-cancer":"https://www.who.int/news-room/fact-sheets/detail/breast-cancer",
    "brucellosis":"https://www.who.int/news-room/fact-sheets/detail/brucellosis",
    "burns":"https://www.who.int/news-room/fact-sheets/detail/burns",
    "buruli-ulcer-(mycobacterium-ulcerans-infection)":"https://www.who.int/news-room/fact-sheets/detail/buruli-ulcer-(mycobacterium-ulcerans-infection)",
    "campylobacter":"https://www.who.int/news-room/fact-sheets/detail/campylobacter",
    "cancer":"https://www.who.int/news-room/fact-sheets/detail/cancer",
    "Candidiasis (yeast infection)":"https://www.who.int/news-room/fact-sheets/detail/candidiasis-(yeast-infection)",
    "cardiovascular-diseases-(cvds)":"https://www.who.int/news-room/fact-sheets/detail/cardiovascular-diseases-(cvds)",
    "cervical-cancer":"https://www.who.int/news-room/fact-sheets/detail/cervical-cancer",
    "chagas-disease-(american-trypanosomiasis)":"https://www.who.int/news-room/fact-sheets/detail/chagas-disease-(american-trypanosomiasis)",
    "chikungunya":"https://www.who.int/news-room/fact-sheets/detail/chikungunya",
    "child-maltreatment":"https://www.who.int/news-room/fact-sheets/detail/child-maltreatment",
    "child-mortality-under-5-years":"https://www.who.int/news-room/fact-sheets/detail/child-mortality-under-5-years",
    "cancer-in-children":"https://www.who.int/news-room/fact-sheets/detail/cancer-in-children",
    "chlamydia":"https://www.who.int/news-room/fact-sheets/detail/chlamydia",
    "cholera":"https://www.who.int/news-room/fact-sheets/detail/cholera",
    "chromoblastomycosis":"https://www.who.int/news-room/fact-sheets/detail/chromoblastomycosis",
    "chronic-obstructive-pulmonary-disease-(copd)":"https://www.who.int/news-room/fact-sheets/detail/chronic-obstructive-pulmonary-disease-(copd)",
    "civil-registration-and-vital-statistics":"https://www.who.int/news-room/fact-sheets/detail/civil-registration-and-vital-statistics",
    "climate-change-and-health":"https://www.who.int/news-room/fact-sheets/detail/climate-change-and-health",
    "colorectal-cancer":"https://www.who.int/news-room/fact-sheets/detail/colorectal-cancer",
    "commercial-determinants-of-health":"https://www.who.int/news-room/fact-sheets/detail/commercial-determinants-of-health",
    "community-based-health-insurance-CBHI":"https://www.who.int/news-room/fact-sheets/detail/community-based-health-insurance-CBHI",
    "condoms":"https://www.who.int/news-room/fact-sheets/detail/condoms",
    "birth-defects":"https://www.who.int/news-room/fact-sheets/detail/birth-defects",
    "coronavirus-disease-(covid-19":"https://www.who.int/news-room/fact-sheets/detail/coronavirus-disease-(covid-19)",
    "corporal-punishment-and-health":"https://www.who.int/news-room/fact-sheets/detail/corporal-punishment-and-health",
    "crimean-congo-haemorrhagic-fever":"https://www.who.int/news-room/fact-sheets/detail/crimean-congo-haemorrhagic-fever",
    "Deafness and hearing loss":"https://www.who.int/news-room/fact-sheets/detail/deafness-and-hearing-loss",
    "deliberate-events":"https://www.who.int/news-room/fact-sheets/detail/deliberate-events",
    "dementia":"https://www.who.int/news-room/fact-sheets/detail/dementia",
    "dengue-and-severe-dengue":"https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue",
    "depression":"https://www.who.int/news-room/fact-sheets/detail/depression",
    "diabetes":"https://www.who.int/news-room/fact-sheets/detail/diabetes",
    "diarrhoeal-disease":"https://www.who.int/news-room/fact-sheets/detail/diarrhoeal-disease",
    "dioxins-and-their-effects-on-human-health":"https://www.who.int/news-room/fact-sheets/detail/dioxins-and-their-effects-on-human-health",
    "diphtheria":"https://www.who.int/news-room/fact-sheets/detail/diphtheria",
    "disability-and-health":"https://www.who.int/news-room/fact-sheets/detail/disability-and-health",
    "dracunculiasis":"https://www.who.int/news-room/fact-sheets/detail/dracunculiasis-(guinea-worm-disease)",
    "drinking-water":"https://www.who.int/news-room/fact-sheets/detail/drinking-water",
    "drowning":"https://www.who.int/news-room/fact-sheets/detail/drowning",
    "e-coli":"https://www.who.int/news-room/fact-sheets/detail/e-coli",
    "ebola-disease":"https://www.who.int/news-room/fact-sheets/detail/ebola-disease",
    "echinococcosis":"https://www.who.int/news-room/fact-sheets/detail/echinococcosis",
    "el-nino-southern-oscillation-(enso)":"https://www.who.int/news-room/fact-sheets/detail/el-nino-southern-oscillation-(enso)",
    "electricity-in-health-care-facilities":"https://www.who.int/news-room/fact-sheets/detail/electricity-in-health-care-facilities",
    "electronic-waste-(e-waste)":"https://www.who.int/news-room/fact-sheets/detail/electronic-waste-(e-waste)",
    "emergency-contraception":"https://www.who.int/news-room/fact-sheets/detail/emergency-contraception",
    "endometriosis":"https://www.who.int/news-room/fact-sheets/detail/endometriosis",
    "epilepsy":"https://www.who.int/news-room/fact-sheets/detail/epilepsy",
    "essential-medicines":"https://www.who.int/news-room/fact-sheets/detail/essential-medicines",
    "falls":"https://www.who.int/news-room/fact-sheets/detail/falls",
    "family-planning-contraception":"https://www.who.int/news-room/fact-sheets/detail/family-planning-contraception",
    "female-genital-mutilation":"https://www.who.int/news-room/fact-sheets/detail/female-genital-mutilation",
    "food-additives":"https://www.who.int/news-room/fact-sheets/detail/food-additives",
    "food-safety":"https://www.who.int/news-room/fact-sheets/detail/food-safety",
    "fragility-fractures":"https://www.who.int/news-room/fact-sheets/detail/fragility-fractures",
    "free-health-care-policies":"https://www.who.int/news-room/fact-sheets/detail/free-health-care-policies",
    "free-health-care-policies":"https://www.who.int/news-room/fact-sheets/detail/free-health-care-policies",
    "gonorrhoea-(neisseria-gonorrhoeae-infection)":"https://www.who.int/news-room/fact-sheets/detail/gonorrhoea-(neisseria-gonorrhoeae-infection)",
    "gambling":"https://www.who.int/news-room/fact-sheets/detail/gambling",
    "guillain-barr%C3%A9-syndrome":"https://www.who.int/news-room/fact-sheets/detail/guillain-barr%C3%A9-syndrome",
    "health-literacy":"https://www.who.int/news-room/fact-sheets/detail/health-literacy",
    "health-care-waste":"https://www.who.int/news-room/fact-sheets/detail/health-care-waste",
    "healthy-diet":"https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
    "climate-change-heat-and-health":"https://www.who.int/news-room/fact-sheets/detail/climate-change-heat-and-health",
    "hepatitis-a":"https://www.who.int/news-room/fact-sheets/detail/hepatitis-a",
    "hepatitis-b":"https://www.who.int/news-room/fact-sheets/detail/hepatitis-b",
    "hepatitis-c":"https://www.who.int/news-room/fact-sheets/detail/hepatitis-c",
    "hepatitis-d":"https://www.who.int/news-room/fact-sheets/detail/hepatitis-d",
    "hepatitis-e":"https://www.who.int/news-room/fact-sheets/detail/hepatitis-e",
    "herpes-simplex-virus":"https://www.who.int/news-room/fact-sheets/detail/herpes-simplex-virus",
    "hiv-aids":"https://www.who.int/news-room/fact-sheets/detail/hiv-aids",
    "hiv-drug-resistance":"https://www.who.int/news-room/fact-sheets/detail/hiv-drug-resistance",
    "household-air-pollution-and-health":"https://www.who.int/news-room/fact-sheets/detail/household-air-pollution-and-health",
    "human-rights-and-health":"https://www.who.int/news-room/fact-sheets/detail/human-rights-and-health",
    "human-papilloma-virus-and-cancer":"https://www.who.int/news-room/fact-sheets/detail/human-papilloma-virus-and-cancer",
    "icd-11":"https://www.who.int/news-room/fact-sheets/detail/icd-11",
    "hypertension":"https://www.who.int/news-room/fact-sheets/detail/hypertension",
    "human-t-lymphotropic-virus-type-1":"https://www.who.int/news-room/fact-sheets/detail/human-t-lymphotropic-virus-type-1",
    "immunization-coverage":"https://www.who.int/news-room/fact-sheets/detail/immunization-coverage",
    "infant-and-young-child-feeding":"https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding",
    "infertility":"https://www.who.int/news-room/fact-sheets/detail/infertility",
    "injuries-and-violence":"https://www.who.int/news-room/fact-sheets/detail/injuries-and-violence",
    "influenza-(avian-and-other-zoonotic)":"https://www.who.int/news-room/fact-sheets/detail/influenza-(avian-and-other-zoonotic)",
    "influenza-(seasonal)":"https://www.who.int/news-room/fact-sheets/detail/influenza-(seasonal)",
    "lassa-fever":"https://www.who.int/news-room/fact-sheets/detail/lassa-fever",
    "low-back-pain":"https://www.who.int/news-room/fact-sheets/detail/low-back-pain",
    "lung-cancer":"https://www.who.int/news-room/fact-sheets/detail/lung-cancer",
    "lead-poisoning-and-health":"https://www.who.int/news-room/fact-sheets/detail/lead-poisoning-and-health",
    "legionellosis":"https://www.who.int/news-room/fact-sheets/detail/legionellosis",
    "leishmaniasis":"https://www.who.int/news-room/fact-sheets/detail/leishmaniasis",
    "leprosy":"https://www.who.int/news-room/fact-sheets/detail/leprosy",
    "listeriosis":"https://www.who.int/news-room/fact-sheets/detail/listeriosis",
    "lymphatic-filariasis":"https://www.who.int/news-room/fact-sheets/detail/lymphatic-filariasis",
    "malaria":"https://www.who.int/news-room/fact-sheets/detail/malaria",
    "malnutrition":"https://www.who.int/news-room/fact-sheets/detail/malnutrition",
    "maternal-mortality":"https://www.who.int/news-room/fact-sheets/detail/maternal-mortality",
    "mental-disorders":"https://www.who.int/news-room/fact-sheets/detail/mental-disorders",
    "mental-health-strengthening-our-response":"https://www.who.int/news-room/fact-sheets/detail/mental-health-strengthening-our-response",
    "mental-health-at-work":"https://www.who.int/news-room/fact-sheets/detail/mental-health-at-work",
    "mental-health-in-emergencies":"https://www.who.int/news-room/fact-sheets/detail/mental-health-in-emergencies",
    "adolescent-mental-health":"https://www.who.int/news-room/fact-sheets/detail/adolescent-mental-health",
    "mental-health-of-older-adults":"https://www.who.int/news-room/fact-sheets/detail/mental-health-of-older-adults",
    "musculoskeletal-conditions":"https://www.who.int/news-room/fact-sheets/detail/musculoskeletal-conditions",
    "ionizing-radiation-and-health-effects":"https://www.who.int/news-room/fact-sheets/detail/ionizing-radiation-and-health-effects",
    "japanese-encephalitis":"https://www.who.int/news-room/fact-sheets/detail/japanese-encephalitis",
    "marburg-virus-disease":"https://www.who.int/news-room/fact-sheets/detail/marburg-virus-disease",
    "measles":"https://www.who.int/news-room/fact-sheets/detail/measles",
    "meningitis":"https://www.who.int/news-room/fact-sheets/detail/meningitis",
    "menopause":"https://www.who.int/news-room/fact-sheets/detail/menopause",
    "mercury-and-health":"https://www.who.int/news-room/fact-sheets/detail/mercury-and-health",
    "middle-east-respiratory-syndrome-coronavirus-(mers-cov)":"https://www.who.int/news-room/fact-sheets/detail/middle-east-respiratory-syndrome-coronavirus-(mers-cov)",
    "headache-disorders":"https://www.who.int/news-room/fact-sheets/detail/headache-disorders",
    "millennium-development-goals-(mdgs)":"https://www.who.int/news-room/fact-sheets/detail/millennium-development-goals-(mdgs)",
    "mpox":"https://www.who.int/news-room/fact-sheets/detail/mpox",
    "multi-drug-resistant-gonorrhoea":"https://www.who.int/news-room/fact-sheets/detail/multi-drug-resistant-gonorrhoea",
    "multiple-sclerosis":"https://www.who.int/news-room/fact-sheets/detail/multiple-sclerosis",
    "mycetoma":"https://www.who.int/news-room/fact-sheets/detail/mycetoma",
    "mycotoxins":"https://www.who.int/news-room/fact-sheets/detail/mycotoxins",
    "natural-toxins-in-food":"https://www.who.int/news-room/fact-sheets/detail/natural-toxins-in-food",
    "newborn-mortality":"https://www.who.int/news-room/fact-sheets/detail/newborn-mortality",
    "nipah-virus":"https://www.who.int/news-room/fact-sheets/detail/nipah-virus",
    "noma":"https://www.who.int/news-room/fact-sheets/detail/noma",
    "noncommunicable-diseases":"https://www.who.int/news-room/fact-sheets/detail/noncommunicable-diseases",
    "nursing-and-midwifery":"https://www.who.int/news-room/fact-sheets/detail/nursing-and-midwifery",
    "obesity-and-overweight":"https://www.who.int/news-room/fact-sheets/detail/obesity-and-overweight",
    "occupational-health--health-workers":"https://www.who.int/news-room/fact-sheets/detail/occupational-health--health-workers",
    "older-children-and-young-adolescent-mortality-(5-to-14-years)":"https://www.who.int/news-room/fact-sheets/detail/older-children-and-young-adolescent-mortality-(5-to-14-years)",
    "onchocerciasis":"https://www.who.int/news-room/fact-sheets/detail/onchocerciasis",
    "one-health":"https://www.who.int/news-room/fact-sheets/detail/one-health",
    "opioid-overdose":"https://www.who.int/news-room/fact-sheets/detail/opioid-overdose",
    "oral-health":"https://www.who.int/news-room/fact-sheets/detail/oral-health",
    "oropouche-virus-disease":"https://www.who.int/news-room/fact-sheets/detail/oropouche-virus-disease",
    "osteoarthritis":"https://www.who.int/news-room/fact-sheets/detail/osteoarthritis",
    "palliative-care":"https://www.who.int/news-room/fact-sheets/detail/palliative-care",
    "parkinson-disease":"https://www.who.int/news-room/fact-sheets/detail/parkinson-disease",
    "patient-safety":"https://www.who.int/news-room/fact-sheets/detail/patient-safety",
    "pesticide-residues-in-food":"https://www.who.int/news-room/fact-sheets/detail/pesticide-residues-in-food",
    "physical-activity":"https://www.who.int/news-room/fact-sheets/detail/physical-activity",
    "plague":"https://www.who.int/news-room/fact-sheets/detail/plague",
    "pneumonia":"https://www.who.int/news-room/fact-sheets/detail/pneumonia",
    "podoconiosis-(non-filarial-lymphoedema)":"https://www.who.int/news-room/fact-sheets/detail/podoconiosis-(non-filarial-lymphoedema)",
    "poliomyelitis":"https://www.who.int/news-room/fact-sheets/detail/poliomyelitis",
    "polycystic-ovary-syndrome":"https://www.who.int/news-room/fact-sheets/detail/polycystic-ovary-syndrome",
    "post-covid-19-condition-(long-covid)":"https://www.who.int/news-room/fact-sheets/detail/post-covid-19-condition-(long-covid)",
    "post-traumatic-stress-disorder":"https://www.who.int/news-room/fact-sheets/detail/post-traumatic-stress-disorder",
    "pre-eclampsia":"https://www.who.int/news-room/fact-sheets/detail/pre-eclampsia",
    "prequalification-of-medicines-by-who":"https://www.who.int/news-room/fact-sheets/detail/prequalification-of-medicines-by-who",
    "preterm-birth":"https://www.who.int/news-room/fact-sheets/detail/preterm-birth",
    "primary-health-care":"https://www.who.int/news-room/fact-sheets/detail/primary-health-care",
    "protecting-workers'-health":"https://www.who.int/news-room/fact-sheets/detail/protecting-workers'-health",
    "quality-health-services":"https://www.who.int/news-room/fact-sheets/detail/quality-health-services",
    "rabies":"https://www.who.int/news-room/fact-sheets/detail/rabies",
    "radon":"https://www.who.int/news-room/fact-sheets/detail/radon-and-health",
    "refugee-and-migrant-health":"https://www.who.int/news-room/fact-sheets/detail/refugee-and-migrant-health",
    "refugee-and-migrant-mental-health":"https://www.who.int/news-room/fact-sheets/detail/refugee-and-migrant-mental-health",
    "rehabilitation":"https://www.who.int/news-room/fact-sheets/detail/rehabilitation",
    "respiratory-syncytial-virus-(rsv)":"https://www.who.int/news-room/fact-sheets/detail/respiratory-syncytial-virus-(rsv)",
    "rheumatic-heart-disease":"https://www.who.int/news-room/fact-sheets/detail/rheumatic-heart-disease",
    "rheumatoid-arthritis":"https://www.who.int/news-room/fact-sheets/detail/rheumatoid-arthritis",
    "rift-valley-fever":"https://www.who.int/news-room/fact-sheets/detail/rift-valley-fever",
    "ringworm":"https://www.who.int/news-room/fact-sheets/detail/ringworm-(tinea)",
    "road-traffic-injuries":"https://www.who.int/news-room/fact-sheets/detail/road-traffic-injuries",
    "rubella":"https://www.who.int/news-room/fact-sheets/detail/rubella",
    "salmonella":"https://www.who.int/news-room/fact-sheets/detail/salmonella-(non-typhoidal)",
    "sand-and-dust-storms":"https://www.who.int/news-room/fact-sheets/detail/sand-and-dust-storms",
    "sanitation":"https://www.who.int/news-room/fact-sheets/detail/sanitation",
    "scabies":"https://www.who.int/news-room/fact-sheets/detail/scabies",
    "schistosomiasis":"https://www.who.int/news-room/fact-sheets/detail/schistosomiasis",
    "schizophrenia":"https://www.who.int/news-room/fact-sheets/detail/schizophrenia",
    "self-care-health-interventions":"https://www.who.int/news-room/fact-sheets/detail/self-care-health-interventions",
    "sepsis":"https://www.who.int/news-room/fact-sheets/detail/sepsis",
    "sexually-transmitted-infections-(stis)":"https://www.who.int/news-room/fact-sheets/detail/sexually-transmitted-infections-(stis)",
    "shingles-(herpes-zoster)":"https://www.who.int/news-room/fact-sheets/detail/shingles-(herpes-zoster)",
    "snakebite-envenoming":"https://www.who.int/news-room/fact-sheets/detail/snakebite-envenoming",
    "social-determinants-of-health":"https://www.who.int/news-room/fact-sheets/detail/social-determinants-of-health",
    "sodium-reduction":"https://www.who.int/news-room/fact-sheets/detail/sodium-reduction",
    "soil-transmitted-helminth-infections":"https://www.who.int/news-room/fact-sheets/detail/soil-transmitted-helminth-infections",
    "spinal-cord-injury":"https://www.who.int/news-room/fact-sheets/detail/spinal-cord-injury",
    "sporotrichosis":"https://www.who.int/news-room/fact-sheets/detail/sporotrichosis",
    "substandard-and-falsified-medical-products":"https://www.who.int/news-room/fact-sheets/detail/substandard-and-falsified-medical-products",
    "sugars-and-dental-caries":"https://www.who.int/news-room/fact-sheets/detail/sugars-and-dental-caries",
    "suicide":"https://www.who.int/news-room/fact-sheets/detail/suicide",
    "syphilis":"https://www.who.int/news-room/fact-sheets/detail/syphilis",
    "taeniasis-cysticercosis":"https://www.who.int/news-room/fact-sheets/detail/taeniasis-cysticercosis",
    "tetanus":"https://www.who.int/news-room/fact-sheets/detail/tetanus",
    "the-top-10-causes-of-death":"https://www.who.int/news-room/fact-sheets/detail/the-top-10-causes-of-death",
    "tobacco":"https://www.who.int/news-room/fact-sheets/detail/tobacco",
    "trachoma":"https://www.who.int/news-room/fact-sheets/detail/trachoma",
    "trans-fat":"https://www.who.int/news-room/fact-sheets/detail/trans-fat",
    "trichomoniasis":"https://www.who.int/news-room/fact-sheets/detail/trichomoniasis",
    "/trypanosomiasis-human-african-(sleeping-sickness)":"https://www.who.int/news-room/fact-sheets/detail/trypanosomiasis-human-african-(sleeping-sickness)",
    "tuberculosis":"https://www.who.int/news-room/fact-sheets/detail/tuberculosis",
    "tungiasis":"https://www.who.int/news-room/fact-sheets/detail/tungiasis",
    "typhoid":"https://www.who.int/news-room/fact-sheets/detail/typhoid",
    "ultraviolet-radiation":"https://www.who.int/news-room/fact-sheets/detail/ultraviolet-radiation",
    "universal-health-coverage-(uhc)":"https://www.who.int/news-room/fact-sheets/detail/universal-health-coverage-(uhc)",
    "urban-health":"https://www.who.int/news-room/fact-sheets/detail/urban-health",
    "vector-borne-diseases":"https://www.who.int/news-room/fact-sheets/detail/vector-borne-diseases",
    "violence-against-children":"https://www.who.int/news-room/fact-sheets/detail/violence-against-children",
    "violence-against-women":"https://www.who.int/news-room/fact-sheets/detail/violence-against-women",
    "west-nile-virus":"https://www.who.int/news-room/fact-sheets/detail/west-nile-virus",
    "white-phosphorus":"https://www.who.int/news-room/fact-sheets/detail/white-phosphorus",
    "yaws":"https://www.who.int/news-room/fact-sheets/detail/yaws",
    "yellow-fever":"https://www.who.int/news-room/fact-sheets/detail/yellow-fever",
    "youth-violence":"https://www.who.int/news-room/fact-sheets/detail/youth-violence",
    "zika-virus":"https://www.who.int/news-room/fact-sheets/detail/zika-virus",
    "zoonoses":"https://www.who.int/news-room/fact-sheets/detail/zoonoses"

}

def clean_text(text):
    # Remove references like [1], [2], [citation needed]
    text = re.sub(r'\[\d+\]', '', text)
    text = re.sub(r'\[citation needed\]', '', text, flags=re.IGNORECASE)

    # Remove pronunciation and native script in parentheses — only at sentence beginning
    text = re.sub(r'\s*\([^\)]{3,100}?\)\s*', ' ', text)

    # Remove excessive whitespace/newlines
    text = re.sub(r'\n+', '\n', text)
    text = re.sub(r'\s{2,}', ' ', text)

    return text.strip()

with open("who_az_guidelines.txt", "w", encoding="utf-8") as outfile:
    for name, url in players.items():
        print(f"Scraping {name}...")
        response = requests.get(url)
        soup = BeautifulSoup(response.text, 'html.parser')

        paragraphs = soup.find_all('p')
        raw_text = "\n".join([p.get_text() for p in paragraphs if p.get_text(strip=True)])
        cleaned = clean_text(raw_text)

        outfile.write(f"\n\n{'='*40}\n{name.replace('_', ' ')}\n{'='*40}\n")
        outfile.write(cleaned)
